apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: es-starter-app
  name: es-starter-app
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: es-starter-app
  type: ClusterIP