apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: dev-es-inst
spec:
  security:
    internalTls: NONE
  # Make sure this Event Streams Operand version is the correct version for the Event Streams Operator version being installed.
  # As of Event Streams Operator versions 3.x, there is no backwards compatibility so the versions of the Event Streams Operator and Operand must match the correct levels.
  version: 11.0.4
  license:
    # By installing this product you accept the license terms at https://ibm.biz/es-license
    accept: true
    use: CloudPakForIntegrationNonProduction
  adminApi: {}
  adminUI: {}
  apicurioRegistry: {}
  collector: {}
  restProducer: {}
  strimziOverrides:
    entityOperator:
      topicOperator: {}
      userOperator: {}
    kafka:
      config:
        inter.broker.protocol.version: '3.2'
        log.message.format.version: '3.2'
        offsets.topic.replication.factor: 1
        transaction.state.log.min.isr: 1
        transaction.state.log.replication.factor: 1
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: metrics-config
      storage:
        type: ephemeral
      replicas: 1
      listeners:
        - name: plain
          port: 9092
          tls: false
          type: internal
        - name: external
          port: 9094
          type: route
          authentication:
            type: scram-sha-512
          tls: true
    zookeeper:
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: metrics-config
      storage:
        type: ephemeral
      replicas: 1
  requestIbmServices:
    iam: true
    monitoring: true